package audit

// RecommendedPolicy is a CIS-aligned AuditPolicy that covers all critical operations.
const RecommendedPolicy = `apiVersion: audit.k8s.io/v1
kind: Policy
# Generated by nodevet --emit-policy
# Based on CIS Kubernetes Benchmark and security best practices.
rules:
  # Log all requests at the Metadata level by default (catch-all at end)

  # Secrets, ConfigMaps, TokenReviews — log full request+response bodies
  - level: RequestResponse
    resources:
      - group: ""
        resources: ["secrets", "configmaps", "serviceaccounts/token"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Pod exec, attach, portforward — log full request body
  - level: Request
    resources:
      - group: ""
        resources: ["pods/exec", "pods/attach", "pods/portforward"]
    verbs: ["get", "create"]

  # Anonymous user actions — log everything at RequestResponse
  - level: RequestResponse
    userGroups: ["system:anonymous"]

  # Node and kubelet operations — log at Metadata
  - level: Metadata
    userGroups: ["system:nodes"]

  # RBAC changes — log at RequestResponse
  - level: RequestResponse
    resources:
      - group: "rbac.authorization.k8s.io"
        resources:
          - "clusterroles"
          - "clusterrolebindings"
          - "roles"
          - "rolebindings"
    verbs: ["create", "update", "patch", "delete"]

  # Admission webhook changes
  - level: RequestResponse
    resources:
      - group: "admissionregistration.k8s.io"
        resources:
          - "mutatingwebhookconfigurations"
          - "validatingwebhookconfigurations"
    verbs: ["create", "update", "patch", "delete"]

  # Skip noisy read-only API discovery requests
  - level: None
    userGroups: ["system:authenticated", "system:unauthenticated"]
    nonResourceURLs:
      - "/api*"
      - "/version"
      - "/healthz"
      - "/readyz"
      - "/livez"

  # Skip leader election chatter
  - level: None
    resources:
      - group: "coordination.k8s.io"
        resources: ["leases"]
    verbs: ["get", "update", "patch"]

  # Default — log all other requests at Metadata level
  - level: Metadata
`
